#!/bin/sh -xe

# Auth to GKE
set +x
echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
gcloud container clusters get-credentials ${CLUSTER_NAME}
set -x

case "$CHART_COMMAND" in
    install)
        chart install -n "$CIRCLE_PROJECT_USERNAME" -r "$CIRCLE_PROJECT_REPONAME" install -f values.yaml
        ;;
    print)
        chart print -n "$CIRCLE_PROJECT_USERNAME" -r "$CIRCLE_PROJECT_REPONAME" install -f values.yaml
        ;;
    *)
        echo 'CHART_COMMAND must be set!'
        exit 1
esac

