#!/bin/sh -xe

set +x
gcloud container clusters get-credentials ${CLUSTER_NAME}
set -x

case "$CHART_COMMAND" in
    install)
        chart install -n "$CIRCLE_PROJECT_USERNAME" -r "$CIRCLE_PROJECT_REPONAME" install -f values.yaml
        ;;
    print)
        chart print -n "$CIRCLE_PROJECT_USERNAME" -r "$CIRCLE_PROJECT_REPONAME" install -f values.yaml
        ;;
    *)
        echo 'CHART_COMMAND must be set!'
        exit 1
esac

