
apiVersion: v1
kind: Service
metadata:
  name: {{ template "template-chart.fullname" . }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: 'http'
  labels:
    app: {{ template "template-chart.name" . }}
    chart: {{ template "template-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    metrics: prometheus
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "template-chart.name" . }}
    release: {{ .Release.Name }}
  ports:
  {{- range .Values.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    protocol: {{ .protocol | default "TCP" }}
  {{- end }}
